source 'https://github.com/CocoaPods/Specs.git'

target 'ViSearch', :exclusive => true do
  pod "ViSearch", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ViSearch", :path => "../"

  pod 'FBSnapshotTestCase'
end
